# --- !Ups

create table "products" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "name" varchar not null,
  "price" int not null
);

create table "carts"(
  "cartId" varchar not null,
  "productName" varchar not null
);

insert into "products" values(2, 'Dove', 21.5);
insert into "products" values(3, 'Bour Bon', 30);
insert into "products" values(4, 'H&S', 90);
insert into "products" values(5, 'Jack & Jones Shirt', 540);
insert into "products" values(6, 'Lee Denim', 1001.5);



# --- !Downs

drop table "products" if exists;
